[package]
name = "gitignore-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
globset = "0.4"
glob = "0.3"
log = "0.4"
tempfile = "3.10"
env_logger = "0.10"
clap = { version = "4.3", features = ["derive"] }
